config/routes.rb
Wele::Application.routes.draw do
  resources :forecasts

  resources :payments

  resources :categories

  resources :accounts

  resources :stakeholders

  resources :cost_centers

end

app/models/cost_center.rb
class CostCenter < ActiveRecord::Base
	validates_presence_of :name
end

app/controllers/cost_centers_controller.rb
class CostCentersController < ApplicationController
  before_action :set_cost_center, only: [:show, :edit, :update, :destroy]

  # GET /cost_centers
  # GET /cost_centers.json
  def index
    @cost_centers = CostCenter.all
  end

  # GET /cost_centers/1
  # GET /cost_centers/1.json
  def show
  end

  # GET /cost_centers/new
  def new
    @cost_center = CostCenter.new
  end

  # GET /cost_centers/1/edit
  def edit
  end

  # POST /cost_centers
  # POST /cost_centers.json
  def create
    @cost_center = CostCenter.new(cost_center_params)

    respond_to do |format|
      if @cost_center.save
        format.html { redirect_to @cost_center, notice: 'Cost center was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cost_center }
      else
        format.html { render action: 'new' }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cost_centers/1
  # PATCH/PUT /cost_centers/1.json
  def update
    respond_to do |format|
      if @cost_center.update(cost_center_params)
        format.html { redirect_to @cost_center, notice: 'Cost center was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_centers/1
  # DELETE /cost_centers/1.json
  def destroy
    @cost_center.destroy
    respond_to do |format|
      format.html { redirect_to cost_centers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_center
      @cost_center = CostCenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_center_params
      params.require(:cost_center).permit(:name)
    end
end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
end

app/views/cost_centers/_form.html.erb
<%= form_for(@cost_center) do |f| %>
  <% if @cost_center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost_center.errors.count, "error") %> prohibited this cost_center from being saved:</h2>

      <ul>
      <% @cost_center.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cost_centers/edit.html.erb
<h1>Editing cost_center</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost_center %> |
<%= link_to 'Back', cost_centers_path %>

app/views/cost_centers/index.html.erb
<h1>Listing cost_centers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cost_centers.each do |cost_center| %>
      <tr>
        <td><%= cost_center.name %></td>
        <td><%= link_to 'Show', cost_center %></td>
        <td><%= link_to 'Edit', edit_cost_center_path(cost_center) %></td>
        <td><%= link_to 'Destroy', cost_center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost center', new_cost_center_path %>

app/views/cost_centers/new.html.erb
<h1>New cost_center</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_centers_path %>

app/views/cost_centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cost_center.name %>
</p>

<%= link_to 'Edit', edit_cost_center_path(@cost_center) %> |
<%= link_to 'Back', cost_centers_path %>