config/routes.rb
Wele::Application.routes.draw do
  resources :forecasts

  resources :payments

  resources :categories

  resources :accounts

  resources :stakeholders

  resources :cost_centers

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:name, :stakeholder_id, :description, :category_id, :payday, :forecast_date, :status, :cost_center_id, :account_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stakeholder_id %><br>
    <%= f.number_field :stakeholder_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :payday %><br>
    <%= f.date_select :payday %>
  </div>
  <div class="field">
    <%= f.label :forecast_date %><br>
    <%= f.date_select :forecast_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :cost_center_id %><br>
    <%= f.number_field :cost_center_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stakeholder</th>
      <th>Description</th>
      <th>Category</th>
      <th>Payday</th>
      <th>Forecast date</th>
      <th>Status</th>
      <th>Cost center</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.name %></td>
        <td><%= payment.stakeholder_id %></td>
        <td><%= payment.description %></td>
        <td><%= payment.category_id %></td>
        <td><%= payment.payday %></td>
        <td><%= payment.forecast_date %></td>
        <td><%= payment.status %></td>
        <td><%= payment.cost_center_id %></td>
        <td><%= payment.account_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment.name %>
</p>

<p>
  <strong>Stakeholder:</strong>
  <%= @payment.stakeholder_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @payment.category_id %>
</p>

<p>
  <strong>Payday:</strong>
  <%= @payment.payday %>
</p>

<p>
  <strong>Forecast date:</strong>
  <%= @payment.forecast_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment.status %>
</p>

<p>
  <strong>Cost center:</strong>
  <%= @payment.cost_center_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @payment.account_id %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>